# Generated by Django 6.0 on 2025-12-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
