# Generated by Django 4.2.27 on 2026-06-13 17:12
#
# NOTE: The production database is ahead of the migration history — the
# Subscriber table, proxy models, and several Job/Tool fields already exist
# (added outside of tracked migrations). Re-creating them here would fail with
# "relation already exists". The ONLY genuinely-new schema change is the
# Job.function field, so this migration is intentionally limited to that.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="function",
            field=models.CharField(
                choices=[
                    ("engineering", "Engineering"),
                    ("operations", "Operations"),
                    ("data", "Data"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
    ]
