# Generated by Django 4.2.27 on 2026-06-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_blogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActiveJob",
            fields=[],
            options={
                "verbose_name": "Active Job",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("jobs.job",),
        ),
        migrations.CreateModel(
            name="UserSubmission",
            fields=[],
            options={
                "verbose_name": "User Submission",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("jobs.job",),
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-is_pinned", "-created_at"]},
        ),
        migrations.AddField(
            model_name="job",
            name="function",
            field=models.CharField(
                choices=[
                    ("engineering", "Engineering"),
                    ("operations", "Operations"),
                    ("data", "Data"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="plan_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full-time"),
                    ("contract", "Contract"),
                    ("part_time", "Part-time"),
                    ("temporary", "Temporary"),
                    ("internship", "Internship"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="tags",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="job",
            name="work_arrangement",
            field=models.CharField(
                choices=[
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("onsite", "On-site"),
                ],
                default="onsite",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="seo_h1",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Page Heading (e.g. 'Top HubSpot Jobs')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="seo_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Browser Title (e.g. 'HubSpot Jobs & Careers')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="blockrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("domain", "Domain"),
                    ("company", "Company"),
                    ("keyword", "Keyword"),
                    ("regex", "Regex"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blockrule",
            name="value",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="apply_url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="job",
            name="company_logo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="screening_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="tools",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="jobs.tool"
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="SEO Content: Appears at top of page."
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["is_active", "screening_status"],
                name="jobs_job_is_acti_ce8017_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["created_at"], name="jobs_job_created_1b3a4d_idx"
            ),
        ),
    ]
