# Generated by Django 4.2.27 on 2026-06-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="pro_waitlist",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pro_waitlist_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
