# Generated by Django 4.2.27 on 2026-06-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_pro_waitlist_userprofile_pro_waitlist_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="desired_role_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="desired_salary",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_announcements",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_newsletter",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="open_to_remote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="twitter_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
