# Generated by Django 4.2.27 on 2026-06-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_desired_role_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProWaitlistEntry",
            fields=[],
            options={
                "verbose_name": "Pro waitlist entry",
                "verbose_name_plural": "Pro Waitlist",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.userprofile",),
        ),
    ]
