"""
Django settings for config project.

Generated by 'django-admin startproject' using Django.
"""
import dj_database_url
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# ==============================================
# SECURITY & PRODUCTION CONFIG
# ==============================================

# SECURITY WARNING: keep the secret key used in production secret!
# On your laptop, it uses the fallback 'insecure' key.
# On Railway, you will add a SECRET_KEY variable.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-mvp-dev-key-12345')

# SECURITY WARNING: don't run with debug turned on in production!
# If 'RENDER' is set in the environment, turn off DEBUG.
if 'RENDER' in os.environ:
    DEBUG = False
else:
    DEBUG = True

# Allow all hosts for MVP
ALLOWED_HOSTS = ['martechstack.onrender.com', 'martechstack.io', 'www.martechstack.io', 'localhost', '127.0.0.1']

# Trusted origins for CSRF (Add the Render domain here)
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com', 
    'https://martechstack.io'
]


# ==============================================
# APPLICATION DEFINITION
# ==============================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third Party
    # (None yet, but 'whitenoise' is handled in Middleware)

    # Your Apps
    'jobs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    # Whitenoise handles CSS/Images in production. MUST be after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # Uses app directories automatically
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ==============================================
# DATABASE
# ==============================================
# Uses SQLite locally, but switches to PostgreSQL on Railway automatically.

# This automatically detects if we are on Render (using DATABASE_URL)
# or on your laptop (using sqlite)
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}

# ==============================================
# PASSWORD VALIDATION
# ==============================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================
# INTERNATIONALIZATION
# ==============================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================================
# STATIC FILES (CSS, JavaScript, Images)
# ==============================================

STATIC_URL = 'static/'

# This is where collectstatic will put all files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Use Whitenoise to serve static files (efficient and simple)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ==============================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ==============================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
